name: Publishable

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - "**.md"
      - "**.yaml"
      - "**.yml"

# Disable permissions for all of the available permissions
permissions: {}

jobs:
  publish-dry-run:
    if: github.repository == 'fluttercandies/flutter_wechat_camera_picker'
    name: Publish dry-run with packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: k-paxian/dart-package-publisher@8fdba1dbf624c712706281a6f91cb50b6bfc2eaf
        with:
          credentialJson: 'MockCredentialJson'
          flutter: true
          dryRunOnly: true
          skipTests: true
