name: Runnable (stable)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

# Disable permissions for all of the available permissions
permissions: {}

jobs:
  analyze:
    name: Analyze on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: flutter-actions/setup-flutter@480ffd9d3a24db4ce099d7ceb62c3d6959661eb8
        with:
          channel: 'stable'
      - run: dart --version
      - run: flutter --version
      - run: flutter pub get
      - run: flutter analyze lib example/lib

  test_iOS:
    needs: analyze
    name: Test iOS on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: flutter-actions/setup-flutter@480ffd9d3a24db4ce099d7ceb62c3d6959661eb8
        with:
          channel: 'stable'
      - run: dart --version
      - run: flutter --version
      - run: flutter pub get
      - run: cd example; flutter build ios --no-codesign

  test_android:
    needs: analyze
    name: Test Android on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: flutter-actions/setup-flutter@480ffd9d3a24db4ce099d7ceb62c3d6959661eb8
        with:
          channel: 'stable'
      - run: dart --version
      - run: flutter --version
      - run: flutter pub get
      - run: cd example; flutter build apk --debug
